name: fiapeats-environment
services:
  postgres:
    container_name: postgres_containner
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dilan_limacampos@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  fiapeats-api:
    container_name: api-container
    build:
      context: .
    image: spring-api
    restart: on-failure
    ports:
      - "8080:8080"

networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: