server:
  port: 8080
  servlet:
    context-path: /fiapeats

spring:
  application:
    name: fiapeats

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true